server:
  port: 8088
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test?characterEncoding=UTF-8
    name: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

